[package]
name = "win_api"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.52.0", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_LibraryLoader"] }