[package]
name = "seventh_databases"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
dotenv = "0.15.0"
futures = "0.3.31"
sqlx = {version = "0.6.3", features = ["runtime-tokio-native-tls","sqlite"]}
tokio = { version = "1.45.1", features = ["full"] }
