[workspace]
resolver = "3"
members = [ "affinity", "channels", "deadlocks", "divide_and_work", "foot_gun", "mutexes", "parking_threads", "poision", "rw_mutexes", "thread2","thread_1", "thread_builder_pattern", "thread_scopes", "workers"]
